networks:
  datasource-network:
    name: datasource-network

services:

  mysql:
    container_name: datasource-mysql-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    profiles:
      - datasource
    networks:
      - datasource-network

  adminer:
    container_name: datasource-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    profiles:
      - datasource
    networks:
      - datasource-network

  ingest-data:
    container_name: ingest-data-yellow-cab
    build:
      dockerfile: './Dockerfiles/ingestion.dockerfile'
    depends_on:
      - mysql
    profiles:
      - data-ingestion
    env_file:
      - .env.local
    volumes:
      - .:/app
    networks:
      - datasource-network

  warehouse:
    container_name: warehouse-warehouse
    image: postgres:13
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/postgresql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    profiles:
      - warehouse
    networks:
    - datasource-network
