services:
  mysql:
    container_name: datasource-mysql-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    profiles:
      - datasource
    networks:
      - tlc-network

  adminer:
    container_name: datasource-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    profiles:
      - datasource
    networks:
      - tlc-network